[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "BMC开发指南"
authors = [{name = "raoxinglong", email = "xinglongrao1204@gmail.com"}]
dynamic = ["version", "description"]
